## Numpy练习

### 1. 创建一个长度为10全为0的一维数组，然后让第5个元素等于1。

In [3]:
import numpy as np
a = np.zeros(10)
print("初始数组：", a)
a[4] = 1
print("修改后的数组：", a)

初始数组： [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
修改后的数组： [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. 生成一个4X5和一个5X4的矩阵，并计算它们的乘积。

In [11]:
import numpy as np

# 生成一个4X5的矩阵
A= np.random.randint(1, 101, size=(4, 5))
print("4X5的矩阵：")
print(A)

# 生成一个5X4的矩阵
B= np.random.randint(1, 101, size=(5, 4))
print("5X4的矩阵：")
print(B)

# 计算两个矩阵的乘积
print("矩阵乘积的结果：")
print(A@B)

4X5的矩阵：
[[27 47 69 11 49]
 [32 99 72 10 96]
 [25 37 78  4 53]
 [ 2 30 88 20 85]]
5X4的矩阵：
[[58  9 24 69]
 [29 49 74 64]
 [58 44 25 37]
 [70 25 44 95]
 [66 92 35 28]]
矩阵乘积的结果：
[[10935 10365  8050  9841]
 [15939 17389 13694 14846]
 [10825 10446  7319  8843]
 [13100 13680  8323  9594]]


### 3. 函数 f 定义如下，其中x是任意实数: 𝑓(𝑥)=(sin⁡(𝑥+1)/𝑒^𝑥 )(𝑥+1)/2，生成一个数组a∈𝑅^5，计算b = f(a)。

In [16]:
import numpy as np

# 生成一个长度为5的整数数组，元素范围是-100到100
a = np.random.randint(-100, 101, size=5)
print("数组a：", a)

# 定义函数f
def f(x):
    return (np.sin(x + 1) / np.exp(x)) * ((x + 1) / 2)

# 计算b = f(a)
b = f(a)
print("数组b = f(a)：", b)

数组a： [  6 -83 -20  92 -89]
数组b = f(a)： [ 5.69977437e-03  1.42918193e+37  6.90794454e+08 -4.88987987e-39
  6.99268564e+38]


### 4. 随机生成一个5行10列的矩阵，然后每行元素减去该行的平均值

In [17]:
import numpy as np

# 随机生成一个5行10列的整数矩阵，元素范围是1到100
matrix = np.random.randint(1, 101, size=(5, 10))
print("原始矩阵：")
print(matrix)

# 计算每行的平均值，结果保留小数
row_means = matrix.mean(axis=1, keepdims=True)
print("每行的平均值：")
print(row_means)

# 每行元素减去该行的平均值
new_matrix = matrix - row_means
print("每行元素减去该行平均值后的矩阵：")
print(new_matrix)

原始矩阵：
[[31  7 60 65 83 26 16 14 59 69]
 [53 73 30 97 71 65 55 51 84 81]
 [92  7 93 81 79 49 43 72 73 17]
 [13 52 38 16 45 89 24 36 52  2]
 [20 31 67 62 32 64 52 59 67 18]]
每行的平均值：
[[43. ]
 [66. ]
 [60.6]
 [36.7]
 [47.2]]
每行元素减去该行平均值后的矩阵：
[[-12.  -36.   17.   22.   40.  -17.  -27.  -29.   16.   26. ]
 [-13.    7.  -36.   31.    5.   -1.  -11.  -15.   18.   15. ]
 [ 31.4 -53.6  32.4  20.4  18.4 -11.6 -17.6  11.4  12.4 -43.6]
 [-23.7  15.3   1.3 -20.7   8.3  52.3 -12.7  -0.7  15.3 -34.7]
 [-27.2 -16.2  19.8  14.8 -15.2  16.8   4.8  11.8  19.8 -29.2]]
